"""Sync models: add UserCredentials and password_hash

Revision ID: 0375c0ed62c6
Revises: d122079a1b36
Create Date: 2025-11-05 01:23:56.501610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0375c0ed62c6'
down_revision = 'd122079a1b36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_credentials', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
