"""tabla comment

Revision ID: 2c63451000de
Revises: acc5a490308a
Create Date: 2024-06-25 19:42:07.411139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c63451000de'
down_revision = 'acc5a490308a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('comment',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('content', sa.Text(), nullable=False),
    # sa.Column('date_created', sa.DateTime(), nullable=True),
    # sa.Column('post_id', sa.Integer(), nullable=False),
    # sa.Column('user_id', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    # sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    pass # Podés agregar un 'pass' para que quede más claro
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('comment')
    pass # Podés agregar un 'pass' para que quede más claro
    # ### end Alembic commands ###