"""column created at on User model

Revision ID: 85296ab118a5
Revises: 0375c0ed62c6
Create Date: 2025-11-05 09:06:27.243302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85296ab118a5'
down_revision = '0375c0ed62c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
